import { Providers } from "@/providers/Providers";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { Footer } from "@/components/footer/footer";
import './globals.css'

const jost = Jost({
  weight: ["100", "200", "300", "400", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Providers>
          <div className="">{children}</div>

          <div className="">
            <Footer />
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
